CREATE TABLE regsignin (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email_address VARCHAR(80) NOT NULL UNIQUE,
    first_name VARCHAR(80) NOT NULL,
    last_name VARCHAR(80),
    password_user VARCHAR(255) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);