CREATE TABLE posts (
    id INT PRIMARY KEY AUTO_INCREMENT,
    UserName VARCHAR(80) NOT NULL,
    media VARCHAR(500),
    paragraph VARCHAR(500),
    bookMark BOOL NOT NULL DEFAULT FALSE,
    removed BOOL NOT NULL DEFAULT FALSE,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE postComments (
    id INT PRIMARY KEY AUTO_INCREMENT,
    postName VARCHAR(80) NOT NULL,
    comment VARCHAR(500),
    removed BOOL NOT NULL DEFAULT FALSE,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE postLikes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    postName VARCHAR(80) NOT NULL,
    likes INT NOT NULL DEFAULT 0,
    liker VARCHAR(80),
    liked BOOL NOT NULL DEFAULT FALSE,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);